### Sentiment Analysis of Musical Instrument in Amazon

## Using Machine Learning Model(SVC)

In [1]:
import pandas as pd

In [2]:
df=pd.read_json('Musical_Instruments.json',lines=True)

In [3]:
df

reviewerID        asin   
0      A2IBPI20UZIR0U  1384719342  \
1      A14VAT5EAX3D9S  1384719342   
2      A195EZSQDW3E21  1384719342   
3      A2C00NNG1ZQQG2  1384719342   
4       A94QU4C90B1AX  1384719342   
...               ...         ...   
10256  A14B2YH83ZXMPP  B00JBIVXGC   
10257   A1RPTVW5VEOSI  B00JBIVXGC   
10258   AWCJ12KBO5VII  B00JBIVXGC   
10259  A2Z7S8B5U4PAKJ  B00JBIVXGC   
10260  A2WA8TDCTGUADI  B00JBIVXGC   

                                           reviewerName   helpful   
0      cassandra tu "Yeah, well, that's just like, u...    [0, 0]  \
1                                                  Jake  [13, 14]   
2                         Rick Bennette "Rick Bennette"    [1, 1]   
3                             RustyBill "Sunday Rocker"    [0, 0]   
4                                         SEAN MASLANKA    [0, 0]   
...                                                 ...       ...   
10256                                   Lonnie M. Adams    [0, 0]   
10257                                Michael J. Edelman    [0, 0]   
10258                                  Michael L. Knapp    [0, 0]   
10259                           Rick Langdon "Scriptor"    [0, 0]   
10260                                   TheTerrorBeyond    [0, 0]   

                                              reviewText  overall   
0      Not much to write about here, but it does exac...        5  \
1      The product does exactly as it should and is q...        5   
2      The primary job of this device is to block the...        5   
3      Nice windscreen protects my MXL mic and preven...        5   
4      This pop filter is great. It looks and perform...        5   
...                                                  ...      ...   
10256            Great, just as expected.  Thank to all.        5   
10257  I've been thinking about trying the Nanoweb st...        5   
10258  I have tried coated strings in the past ( incl...        4   
10259  Well, MADE by Elixir and DEVELOPED with Taylor...        4   
10260  These strings are really quite good, but I wou...        4   

                                                 summary  unixReviewTime   
0                                                   good      1393545600  \
1                                                   Jake      1363392000   
2                                   It Does The Job Well      1377648000   
3                          GOOD WINDSCREEN FOR THE MONEY      1392336000   
4                  No more pops when I record my vocals.      1392940800   
...                                                  ...             ...   
10256                                         Five Stars      1405814400   
10257  Long life, and for some players, a good econom...      1404259200   
10258                                   Good for coated.      1405987200   
10259                                        Taylor Made      1404172800   
10260  These strings are really quite good, but I wou...      1405468800   

        reviewTime  
0      02 28, 2014  
1      03 16, 2013  
2      08 28, 2013  
3      02 14, 2014  
4      02 21, 2014  
...            ...  
10256  07 20, 2014  
10257   07 2, 2014  
10258  07 22, 2014  
10259   07 1, 2014  
10260  07 16, 2014  

[10261 rows x 9 columns]

In [17]:
df['overall'].unique()

array([5, 3, 4, 2, 1], dtype=int64)

In [27]:
final_df=df[['reviewText','overall']]

In [28]:
import re 
for i in final_df['reviewText']:
    i=re.sub('[^a-zA-Z0-9]',"",i)
    i=i.lower()

In [44]:
from sklearn.model_selection import train_test_split
X=final_df['reviewText']
y=df['overall']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
vector=TfidfVectorizer()
X_train=vector.fit_transform(X_train)

In [46]:
from sklearn.svm import SVC
model=SVC()
model.fit(X_train,y_train)

SVC()

In [47]:
from sklearn.metrics import classification_report
X_test=vector.transform(X_test)
y_pred=model.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        43
           2       0.00      0.00      0.00        55
           3       1.00      0.02      0.04       159
           4       0.52      0.04      0.08       387
           5       0.70      1.00      0.82      1409

    accuracy                           0.69      2053
   macro avg       0.44      0.21      0.19      2053
weighted avg       0.65      0.69      0.58      2053



E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [69]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[   0,    0,    0,    0,   43],
       [   0,    0,    0,    2,   53],
       [   0,    0,    3,    8,  148],
       [   0,    0,    0,   16,  371],
       [   0,    0,    0,    5, 1404]], dtype=int64)

In [67]:
X=['Well, MADE by Elixir and DEVELOPED with Taylor']
X_input=vector.transform(X)


In [68]:
model.predict(X_input)

array([5], dtype=int64)

In [70]:
from sklearn.naive_bayes import MultinomialNB
model1=MultinomialNB()
model1.fit(X_train,y_train)

MultinomialNB()

In [72]:
y_pred1=model1.predict(X_test)
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        43
           2       0.00      0.00      0.00        55
           3       0.00      0.00      0.00       159
           4       0.00      0.00      0.00       387
           5       0.69      1.00      0.81      1409

    accuracy                           0.69      2053
   macro avg       0.14      0.20      0.16      2053
weighted avg       0.47      0.69      0.56      2053



E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [73]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(X_train,y_train)

RandomForestClassifier()

In [74]:
y_pred2=model2.predict(X_test)
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        43
           2       1.00      0.02      0.04        55
           3       0.00      0.00      0.00       159
           4       0.50      0.01      0.01       387
           5       0.69      1.00      0.81      1409

    accuracy                           0.69      2053
   macro avg       0.44      0.20      0.17      2053
weighted avg       0.59      0.69      0.56      2053



E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\BROCAMP\DS\dsvenv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [76]:
X=['Very Bad product Recieved']
X_input=vector.transform(X)
model2.predict(X_input)

array([5], dtype=int64)

# *************************************************************

### Using NLTK

In [4]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Error loading vader_lexicon: <urlopen error [WinError
[nltk_data]     10060] A connection attempt failed because the
[nltk_data]     connected party did not properly respond after a
[nltk_data]     period of time, or established connection failed
[nltk_data]     because connected host has failed to respond>
[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


False

In [5]:
df1=df[['reviewText','overall']]
df1

reviewText  overall
0      Not much to write about here, but it does exac...        5
1      The product does exactly as it should and is q...        5
2      The primary job of this device is to block the...        5
3      Nice windscreen protects my MXL mic and preven...        5
4      This pop filter is great. It looks and perform...        5
...                                                  ...      ...
10256            Great, just as expected.  Thank to all.        5
10257  I've been thinking about trying the Nanoweb st...        5
10258  I have tried coated strings in the past ( incl...        4
10259  Well, MADE by Elixir and DEVELOPED with Taylor...        4
10260  These strings are really quite good, but I wou...        4

[10261 rows x 2 columns]

In [ ]:
from nltk.tokenize import word_tokenize

In [6]:
def preprocess_text(text):
    import nltk
    from nltk.corpus import stopwords
    from nltk.tokenize import word_tokenize
    from nltk.sentiment import SentimentIntensityAnalyzer
    tokens=word_tokenize(text.lower())
    filtered_tokens = [token for token in tokens if token not in stopwords.words('english')]
    p_text=' '.join(filtered_tokens)
    return p_text

In [57]:
df1.loc[:, 'p_text'] = df1['reviewText'].apply(preprocess_text)

In [58]:
df1.head()

reviewText  overall   
0  Not much to write about here, but it does exac...        5  \
1  The product does exactly as it should and is q...        5   
2  The primary job of this device is to block the...        5   
3  Nice windscreen protects my MXL mic and preven...        5   
4  This pop filter is great. It looks and perform...        5   

                                              p_text  
0  much write , exactly 's supposed . filters pop...  
1  product exactly quite affordable.i realized do...  
2  primary job device block breath would otherwis...  
3  nice windscreen protects mxl mic prevents pops...  
4  pop filter great . looks performs like studio ...

In [8]:
def predict_sentiment(text):
    from nltk.sentiment import SentimentIntensityAnalyzer
    sia=SentimentIntensityAnalyzer()
    sentiment_scores = sia.polarity_scores(text)
    sentiment = sentiment_scores['compound']
    
    if sentiment >= 0.05:
        return 'Positive'
    elif sentiment <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'

In [23]:
df1['predict']=df1['p_text'].apply(predict_sentiment)

C:\Users\aksha\AppData\Local\Temp\ipykernel_22356\2501530891.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['predict']=df1['p_text'].apply(predict_sentiment)


In [9]:
a='It is bad, but it is good'
predict_sentiment(a)


'Positive'

### Using Roberta Pretrained Model
#### ---> Model Trained of a large Corpus of Data
#### ---> Transformed model accounts for the words but also the context related to other words

In [4]:
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from scipy.special import softmax

In [6]:
import torch
from transformers import AutoTokenizer
MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)

model = AutoModelForSequenceClassification.from_pretrained(MODEL)

E:\BROCAMP\DS\dsvenv\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\aksha\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [22]:
# def text_analysis(text):
#     text=tokenizer(text,return_tensors='pt')
#     output=model(**text)
#     scores=output[0][0].detach().numpy()
#     scores=softmax(scores)
#     scores_dict={'negative':scores[0],'nuetral':scores[1],'poitive':scores[2]}
#     max_score=0
#     for i in scores_dict.keys():
#         if scores_dict[i]>max_score:
#             max_score=scores_dict[i]
#             key=i
#     return key


In [12]:
sample=df.sample(n=10)

In [13]:
sample.head()

reviewerID        asin                   reviewerName helpful   
8162  A1CL807EOUPVP1  B003VWJ2K8                        GunHawk  [0, 0]  \
2614  A206T0W1VE8K1Q  B0002GXZK4                        C3p-BRO  [0, 0]   
3671  A2CZIZD0RZ566T  B0006NDF8A                   EMIL D RUIAN  [0, 0]   
3010  A2074KEJGRYJV4  B0002IHFVM                         hcross  [0, 0]   
3349  A3IS1RBMOOULWI  B0002M72JS  Secret Squirrel "S. Squirrel"  [3, 4]   

                                             reviewText  overall   
8162  I've heard about the Snark tuners before, and ...        5  \
2614  Highest quality guitar I've ever seen in this ...        5   
3671  Easy to take apart, to put together, to store,...        5   
3010  I have a Taylor 710ce and this strap had to be...        2   
3349  Like the previous reviewer, I bought this to s...        5   

                         summary  unixReviewTime   reviewTime  
8162           Something for me.      1375920000   08 8, 2013  
2614                Unbelievable      1384992000  11 21, 2013  
3671           Good space saver.      1371513600  06 18, 2013  
3010  Does not fit Taylor Guitar      1379289600  09 16, 2013  
3349                        Yup!      1298246400  02 21, 2011

In [14]:
sample['p_text']=sample['reviewText'].apply(preprocess_text)

In [16]:
sample.head()

reviewerID        asin                   reviewerName helpful   
8162  A1CL807EOUPVP1  B003VWJ2K8                        GunHawk  [0, 0]  \
2614  A206T0W1VE8K1Q  B0002GXZK4                        C3p-BRO  [0, 0]   
3671  A2CZIZD0RZ566T  B0006NDF8A                   EMIL D RUIAN  [0, 0]   
3010  A2074KEJGRYJV4  B0002IHFVM                         hcross  [0, 0]   
3349  A3IS1RBMOOULWI  B0002M72JS  Secret Squirrel "S. Squirrel"  [3, 4]   

                                             reviewText  overall   
8162  I've heard about the Snark tuners before, and ...        5  \
2614  Highest quality guitar I've ever seen in this ...        5   
3671  Easy to take apart, to put together, to store,...        5   
3010  I have a Taylor 710ce and this strap had to be...        2   
3349  Like the previous reviewer, I bought this to s...        5   

                         summary  unixReviewTime   reviewTime   
8162           Something for me.      1375920000   08 8, 2013  \
2614                Unbelievable      1384992000  11 21, 2013   
3671           Good space saver.      1371513600  06 18, 2013   
3010  Does not fit Taylor Guitar      1379289600  09 16, 2013   
3349                        Yup!      1298246400  02 21, 2011   

                                                 p_text  
8162  've heard snark tuners , seen awhile , skimmin...  
2614  highest quality guitar 've ever seen price ran...  
3671  easy take apart , put together , store , prett...  
3010  taylor 710ce strap forced top connection near ...  
3349  like previous reviewer , bought switch stock o...

In [10]:
def text_analysis(text):
    from transformers import AutoTokenizer
    from transformers import AutoModelForSequenceClassification
    from scipy.special import softmax
    MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
    tokenizer = AutoTokenizer.from_pretrained(MODEL)
    model = AutoModelForSequenceClassification.from_pretrained(MODEL)
    text =tokenizer.encode_plus(
        text,
        max_length=512,  # Set an appropriate value for your specific tokenizer
        truncation=True,
        padding='max_length',
        return_tensors='pt'
    )
    output = model(**text)
    scores = output.logits[0].detach().numpy()
    scores = softmax(scores)
    scores_dict = {'negative': scores[0], 'neutral': scores[1], 'positive': scores[2]}
    max_score = 0
    key = ''
    for i in scores_dict.keys():
        if scores_dict[i] > max_score:
            max_score = scores_dict[i]
            key = i
    return key


In [17]:
sample['sentiment Analysis']=sample['p_text'].apply(text_analysis)

In [20]:
text_analysis("The product is very waste")

'negative'

In [19]:
sample['sentiment Analysis']

8162    positive
2614    positive
3671    positive
3010     neutral
3349    positive
8556    positive
9068    positive
4410     neutral
2687     neutral
9623    positive
Name: sentiment Analysis, dtype: object